# Generated by Django 6.0.4 on 2026-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high'), ('Critical High', 'critical_high')], default='low', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'todo'), ('In progress', 'in_progress'), ('Done', 'done')], default='todo', max_length=15),
        ),
    ]
